include:
  - ../database/docker-compose.yml

services:
  website:
    image: javr-domain:alpine-latest
    build:
      context: ..
      dockerfile: website/Dockerfile
    network_mode: host
    environment:
      - NODE_ENV=${NODE_ENV}
      - ZEROTIER_KEY=${ZEROTIER_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./configs:/app/website/configs
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    network_mode: host
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped